package request

import (
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"net/http"

	"github.com/RingierIMU/rsb-go-lib/v9/base"
	"github.com/gin-gonic/gin"
	_ "github.com/swaggo/gin-swagger/example/basic/docs" // docs is generated by Swag CLI, you have to import it.
)

var (
	router = gin.New()
)

func StartWebServer() {
	apiEventsHandler()
	landingCheck()

	url := ginSwagger.URL("http://localhost:8080/swagger/doc.json") // The url pointing to API definition
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))

	router.Run()
}

// Main page, mainly for load balancers health check
func landingCheck() *gin.Engine {
	router.GET("/", func(context *gin.Context) {
		context.String(http.StatusOK, "I'm alright, thank you!")
	})

	return router
}

// Requests entry point
func apiEventsHandler() *gin.Engine {
	defer base.RecoverFromPanic("apiEventsHandler")

	v1 := router.Group("/api")
	route(v1)

	return router
}
