name: Notify new version

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    name: Notify release
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_WEBHOOK }}
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: notify
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"News…"}' ${SLACK_BOT_TOKEN}
